import {extractDimensions,extractTextDimensions,selectMatches,safeHttpUrl} from './dimensions.mjs';
const retailers=['ikea.com','wayfair.com','amazon.com','target.com','walmart.com','westelm.com','potterybarn.com','crateandbarrel.com','cb2.com','article.com','hermanmiller.com','designwithinreach.com','dwr.com','steelcase.com','staples.com','homedepot.com','lowes.com','ashleyfurniture.com','ashleyhomestore.com','castlery.com','roomandboard.com','flexispot.com','branchfurniture.com','upliftdesk.com'];
export function allowedListing(value){try{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password&&(!u.port||u.port==='443')&&retailers.some(h=>u.hostname===h||u.hostname.endsWith('.'+h));}catch{return false;}}
class SearchError extends Error{constructor(message,status=502){super(message);this.status=status;}}
async function readLimited(response,limit){if(Number(response.headers.get('content-length'))>limit)throw new Error('Response too large');const reader=response.body.getReader();let total=0,chunks=[];try{while(true){const {value,done}=await reader.read();if(done)break;total+=value.length;if(total>limit)throw new Error('Response too large');chunks.push(value);}}finally{await reader.cancel().catch(()=>{});}const joined=new Uint8Array(total);let offset=0;for(const c of chunks){joined.set(c,offset);offset+=c.length;}return new TextDecoder().decode(joined);}
async function serp(parameters,key,fetcher){const url=new URL('https://serpapi.com/search.json');Object.entries({...parameters,api_key:key}).forEach(([k,v])=>url.searchParams.set(k,v));let response;try{response=await fetcher(url,{signal:AbortSignal.timeout(65000)});}catch{throw new SearchError('Google image search timed out. Your photo is still here; try again.');}if(response.status===401||response.status===403)throw new SearchError('SerpApi rejected the key. Check your API key and account access.',401);if(response.status===429)throw new SearchError('SerpApi search quota reached. Check your plan or try later.',429);if(!response.ok)throw new SearchError('The search provider is unavailable. Please try again.');const data=JSON.parse(await readLimited(response,3*1024*1024));if(data.error){if(/no results|hasn.t returned any results|no match/i.test(data.error))return {visual_matches:[],organic_results:[]};throw new SearchError(/credit|limit|quota|run out/i.test(data.error)?'Your SerpApi account has no search credits available.':'Search could not complete. Check your SerpApi key and account, then retry.');}return data;}
async function listingDimensions(url,fetcher){let current=url;for(let i=0;i<3;i++){if(!allowedListing(current))return null;const res=await fetcher(current,{redirect:'manual',signal:AbortSignal.timeout(9000),headers:{Accept:'text/html'}});if(res.status>=300&&res.status<400){const location=res.headers.get('location');if(!location)return null;current=new URL(location,current).href;continue;}if(!res.ok||!res.headers.get('content-type')?.includes('text/html'))return null;const parsed=extractDimensions(await readLimited(res,2*1024*1024));return {...parsed,url:current};}return null;}
function count(d){return Object.values(d).filter(v=>v!==null).length;}
async function enrich(match,key,fetcher){let parsed;try{parsed=await listingDimensions(match.url,fetcher);}catch{}if(parsed&&count(parsed.dimensions)){return {...match,dimensions:parsed.dimensions,evidence:parsed.evidence,dimensionUrl:parsed.url,dimensionStatus:'found',method:parsed.method};}
  // Search the returned product title on the same retailer, then parse a single
  // result at a time. Never combine axes across different pages or variants.
  try{const host=new URL(match.url).hostname;const data=await serp({engine:'google',q:'site:'+host+' "'+match.title.replace(/["<>]/g,'').slice(0,160)+'" dimensions width depth height',num:'5',hl:'en'},key,fetcher);const pages=(data.organic_results||[]).filter(r=>{try{return new URL(r.link).hostname===host;}catch{return false;}});let best=null;for(const p of pages){const extras=p.rich_snippet?.bottom?.detected_extensions;const text=[p.snippet,...(p.rich_snippet?.bottom?.extensions||[]),extras?JSON.stringify(extras):''].join(' ');const extracted=extractTextDimensions(text);if(count(extracted.dimensions)>(best?count(best.dimensions):0))best={...extracted,url:safeHttpUrl(p.link)};}if(best)return {...match,dimensions:best.dimensions,evidence:best.evidence,dimensionUrl:best.url,dimensionStatus:'found',method:'search-snippet',note:'Dimensions from a same-retailer search result. Check the exact model and size variant.'};}catch(error){return {...match,dimensionStatus:'unavailable',note:'Match found, but the dimension lookup could not finish. Enter dimensions manually or retry.'};}return {...match,note:'No unambiguous labelled dimensions found. Open the listing or enter them manually.'};}
export async function runImageSearch(image,key,fetcher=fetch){
  if(typeof key!=='string'||key.length<10||key.length>256||/\s/.test(key))throw new SearchError('Add a valid SerpApi API key in Search setup.',400);
  if(!image||typeof image.arrayBuffer!=='function'||image.size<1||image.size>500000||!['image/jpeg','image/png','image/webp'].includes(image.type))throw new SearchError('Use a JPEG, PNG, or WebP image under 500 KB after compression.',400);
  const form=new FormData();form.append('api_key',key);form.append('image',image,'furniture.jpg');let upload;try{upload=await fetcher('https://serpapi.com/image',{method:'POST',body:form,signal:AbortSignal.timeout(25000)});}catch{throw new SearchError('Photo upload timed out. Try again.');}if(upload.status===401||upload.status===403)throw new SearchError('SerpApi rejected your key. Check it in Search setup.',401);if(!upload.ok)throw new SearchError('The search provider could not accept this photo. Check your key and try another image.');const uploaded=JSON.parse(await readLimited(upload,100000));if(!uploaded.image_id)throw new SearchError('The image provider did not return an image ID. Check your SerpApi account.');
  const data=await serp({engine:'google_lens',image_id:uploaded.image_id,type:'visual_matches',hl:'en'},key,fetcher);const matches=selectMatches(data);const results=await Promise.all(matches.map(m=>enrich(m,key,fetcher)));return {matches:results,note:'Likely visual matches, not verified identities. Dimensions come from listings or indexed snippets, not a physical measurement of your photo.'};
}
export async function handleApi(request,env={},fetcher=fetch){const path=new URL(request.url).pathname;const json=(body,status=200)=>Response.json(body,{status,headers:{'Cache-Control':'no-store'}});if(path==='/api/status'&&request.method==='GET')return json({configured:!!env.SERPAPI_API_KEY});if(path!=='/api/search')return json({error:'Not found'},404);if(request.method!=='POST')return json({error:'Use POST'},405);const origin=request.headers.get('origin');if(origin&&origin!==new URL(request.url).origin)return json({error:'Cross-origin requests are not allowed'},403);if(Number(request.headers.get('content-length'))>700000)return json({error:'Image request is too large'},413);
  try{const contentType=request.headers.get('content-type')||'';if(!contentType.startsWith('multipart/form-data'))return json({error:'Upload an image as multipart form data.'},400);const reader=request.body.getReader();let size=0,chunks=[];while(true){const {value,done}=await reader.read();if(done)break;size+=value.length;if(size>700000){await reader.cancel();return json({error:'Image request is too large'},413);}chunks.push(value);}const blob=new Blob(chunks,{type:contentType});const form=await new Response(blob,{headers:{'Content-Type':contentType}}).formData();const key=env.SERPAPI_API_KEY||request.headers.get('x-serpapi-key')||'';return json(await runImageSearch(form.get('image'),key,fetcher));}catch(error){return json({error:error instanceof SearchError?error.message:'The lookup could not complete. Your dimensions are unchanged; please retry.'},error instanceof SearchError?error.status:502);}}
