const $=id=>document.getElementById(id),axes=['width','depth','height'];
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeUrl=value=>{try{const u=new URL(value);return ['https:','http:'].includes(u.protocol)?u.href:null;}catch{return null;}};
let key='',configured=false,imageBlob=null,imageUrl=null,matches=[],activeMatch=null,controller=null,epoch=0;
const sources={width:null,depth:null,height:null};
function notice(text){$('notice').textContent=text;}
function status(text,error=false){$('search-status').textContent=text;$('search-status').classList.toggle('error',error);}
function connection(){ $('connection').textContent=configured?'Server key configured':key?'Key ready for this session':'Add your SerpApi key';$('forget-key').hidden=!key;}
fetch('/api/status').then(r=>r.json()).then(data=>{configured=!!data.configured;connection();}).catch(()=>{$('connection').textContent='Search server unavailable';});
$('key-form').onsubmit=e=>{e.preventDefault();const candidate=$('api-key').value.trim();if(candidate.length<10||candidate.length>256||/\s/.test(candidate))return notice('Paste your SerpApi API key.');key=candidate;$('api-key').value='';connection();$('setup').open=false;notice('Key set for this session. Select a photo and run the search.');};
$('forget-key').onclick=()=>{key='';$('api-key').value='';connection();notice('Session key cleared.');};
$('choose').onclick=()=>$('photo-file').click();$('take').onclick=()=>$('camera-file').click();
function clearResult(){matches=[];activeMatch=null;$('results').hidden=true;$('matches').innerHTML='';$('item-name').value='';$('identity-note').textContent='Search to identify an item, or enter what you know.';$('dimension-evidence').hidden=true;for(const axis of axes){$(axis).value='';sources[axis]=null;$(axis+'-source').textContent='Not set';}}
function stop(){epoch++;controller?.abort();controller=null;$('cancel').hidden=true;$('search').disabled=!imageBlob;$('search').innerHTML='Search Google Images <span aria-hidden="true">↗</span>';}
$('cancel').onclick=()=>{stop();status('Stopped waiting. The provider may still finish processing this search.');};
async function compress(file){const bitmap=await createImageBitmap(file,{imageOrientation:'from-image'});try{let size=1400;for(let attempt=0;attempt<6;attempt++){const scale=Math.min(1,size/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const ctx=canvas.getContext('2d');ctx.fillStyle='#ffffff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.84-attempt*.06));if(blob&&blob.size<=480000)return blob;size=Math.round(size*.8);}throw new Error('Could not reduce the photo size. Choose a smaller image.');}finally{bitmap.close();}}
async function loadPhoto(file){if(!file)return;if(file.size>20*1024*1024)return notice('Use a photo under 20 MB.');if(!file.type.startsWith('image/'))return notice('Choose an image file.');stop();const ticket=epoch;status('Preparing photo…');try{const blob=await compress(file);if(ticket!==epoch)return;clearResult();if(imageUrl)URL.revokeObjectURL(imageUrl);imageBlob=blob;imageUrl=URL.createObjectURL(blob);$('preview').src=imageUrl;$('preview').hidden=false;$('placeholder').hidden=true;$('file-name').textContent=file.name;$('file-name').title=file.name;$('search').disabled=false;status('Ready to search.');notice('');}catch(error){status('Could not open this photo. Try JPEG, PNG, or WebP; convert HEIC to JPEG if needed.',true);}}
for(const id of ['photo-file','camera-file'])$(id).onchange=e=>{loadPhoto(e.target.files[0]);e.target.value='';};
for(const type of ['dragenter','dragover'])$('drop-zone').addEventListener(type,e=>{e.preventDefault();$('drop-zone').classList.add('dragover');});
for(const type of ['dragleave','drop'])$('drop-zone').addEventListener(type,e=>{e.preventDefault();$('drop-zone').classList.remove('dragover');if(type==='drop')loadPhoto(e.dataTransfer.files[0]);});
$('reset').onclick=()=>{stop();if(imageUrl)URL.revokeObjectURL(imageUrl);imageUrl=null;imageBlob=null;$('preview').removeAttribute('src');$('preview').hidden=true;$('placeholder').hidden=false;$('file-name').textContent='';$('search').disabled=true;clearResult();status('');notice('');};
for(const axis of axes)$(axis).oninput=()=>{sources[axis]=$(axis).value===''?null:'manual';$(axis+'-source').textContent=sources[axis]?'Edited manually':'Not set';};
function renderMatches(){$('matches').innerHTML=matches.map((m,i)=>`<article class="match ${activeMatch===i?'selected':''}">${safeUrl(m.thumbnail)?`<img class="thumb" src="${escape(safeUrl(m.thumbnail))}" alt="" loading="lazy" referrerpolicy="no-referrer">`:'<div class="thumb"></div>'}<div><span class="rank">${i===0?'Top visual match':'Match '+(i+1)}${activeMatch===i?' · selected':''}</span><h3><a href="${escape(safeUrl(m.url))}" target="_blank" rel="noopener noreferrer">${escape(m.title)}</a></h3><p>${escape(m.source)}</p><p class="found">${axes.map(a=>a[0].toUpperCase()+': '+(m.dimensions[a]??'—')).join(' · ')} cm</p><p>${escape(m.note||'Check the product and size variant before using these dimensions.')}</p></div><button class="secondary" data-index="${i}">Use this match</button></article>`).join('');$('matches').querySelectorAll('button').forEach(b=>b.onclick=()=>applyMatch(Number(b.dataset.index),true));$('matches').querySelectorAll('img').forEach(img=>img.onerror=()=>{img.hidden=true;});}
function applyMatch(index,overwrite=false){const m=matches[index];if(!m)return;activeMatch=index;$('item-name').value=m.title;$('identity-note').textContent='Likely match · '+m.source+' · exact variant unverified';let kept=false;for(const axis of axes){if(!overwrite&&sources[axis]==='manual'){kept=true;continue;}const value=m.dimensions[axis];$(axis).value=value??'';sources[axis]=value===null||value===undefined?null:'listing';$(axis+'-source').textContent=sources[axis]?'From likely listing':'Not found · enter manually';}const url=safeUrl(m.dimensionUrl);$('dimension-evidence').hidden=!url;if(url){$('dimension-link').href=url;$('evidence').textContent=m.evidence;}renderMatches();if(kept)notice('Likely match selected. Your manually entered dimensions were preserved.');else if(overwrite)notice('Selected this match. Review or edit its dimensions.');}
$('search').onclick=async()=>{if(!imageBlob)return;if(!configured&&!key){$('setup').open=true;$('api-key').focus();return status('Add your SerpApi key above to run a real image search.',true);}controller?.abort();const ticket=++epoch;controller=new AbortController();$('search').disabled=true;$('search').textContent='Searching…';$('cancel').hidden=false;status('Finding likely products and looking up dimensions. This may take a minute.');notice('');const form=new FormData();form.append('image',imageBlob,'furniture.jpg');try{const response=await fetch('/api/search',{method:'POST',headers:key?{'x-serpapi-key':key}:{},body:form,signal:controller.signal});const data=await response.json();if(ticket!==epoch)return;if(!response.ok)throw new Error(data.error||'Search could not complete.');matches=data.matches||[];$('results').hidden=!matches.length;if(!matches.length){status('No likely match found. Try another angle or enter dimensions manually.');return;}applyMatch(0);status('Found '+matches.length+' likely '+(matches.length===1?'match':'matches')+'. Review the selected item and its dimensions.');}catch(error){if(ticket!==epoch)return;status(error.name==='AbortError'?'Search stopped.':error.message||'Could not connect to the search server.',true);}finally{if(ticket===epoch){controller=null;$('search').disabled=!imageBlob;$('search').innerHTML='Search Google Images <span aria-hidden="true">↗</span>';$('cancel').hidden=true;}}};
function output(){const dimensions={};for(const axis of axes){const value=$(axis).value;if(value!==''&&(!Number.isFinite(Number(value))||Number(value)<=0||Number(value)>20000))throw new Error('Enter positive dimensions in centimeters, or leave unknown values blank.');dimensions[axis]=value===''?null:Number(value);}const match=activeMatch===null?null:matches[activeMatch];return {item:$('item-name').value,units:'cm',dimensions,sources:{...sources},likelyProductUrl:match?.url??null,dimensionSourceUrl:match?.dimensionUrl??null,evidence:match?.evidence??null,identityVerified:false};}
$('copy').onclick=async()=>{try{const result=output();await navigator.clipboard.writeText((result.item||'Furniture')+'\n'+axes.map(a=>a[0].toUpperCase()+a.slice(1)+': '+(result.dimensions[a]===null?'unknown':result.dimensions[a]+' cm')).join('\n'));notice('Dimensions copied.');}catch(error){notice(error.message||'Could not copy. Use Export JSON instead.');}};
$('export').onclick=()=>{try{const url=URL.createObjectURL(new Blob([JSON.stringify(output(),null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='furniture-dimensions.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notice('Exported dimensions and their sources.');}catch(error){notice(error.message);}};
if(document.modelContext?.registerTool){const life=new AbortController();addEventListener('pagehide',()=>life.abort(),{once:true});try{Promise.resolve(document.modelContext.registerTool({name:'read_dimension_result',description:'Read the selected likely furniture item, editable dimensions in centimeters, and dimension sources. Never includes the API key or photo.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:output},{signal:life.signal})).catch(()=>{});}catch{}}
